# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "yunus-sun"
repo_name: "yunus-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
  # Subjects
  "Communications":
    filters: ["Communication", "Network"]
  "Data Center":
    filters: ["Data Center"]
  "Time Series":
    filters: ["Time Series"]
  "RAG":
    filters: ["RAG", "Retrieval-Augmented Generation"]
  # Methods
  "Large Model":
    filters: ["LLM", "Large Model",]
  "Generative AI":
    filters: ["Generative AI"]
  "Reinforcement Learning":
    filters: ["Reinforcement Learning"]
  "Federated Learning":
    filters: ["Federated Learning"]
